package Menu;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AlumnosET20
 */
public class Creditos extends javax.swing.JFrame {

    /**
     * Creates new form Creditos
     */
    public Creditos() {
        initComponents();
        setLocationRelativeTo(null); /* Centra la ventana que se abre */
        setResizable(false); /* Le prohibe al usuario editar el tamaño*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Creditos_Panel = new javax.swing.JPanel();
        Creditos_Label1 = new javax.swing.JLabel();
        Creditos_Label2 = new javax.swing.JLabel();
        Creditos_Label3 = new javax.swing.JLabel();
        Creditos_Label4 = new javax.swing.JLabel();
        Creditos_Label5 = new javax.swing.JLabel();
        Creditos_Label6 = new javax.swing.JLabel();
        Creditos_Label7 = new javax.swing.JLabel();
        Creditos_Boton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Creditos");

        Creditos_Panel.setBackground(new java.awt.Color(0, 0, 0));

        Creditos_Label1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Creditos_Label1.setForeground(new java.awt.Color(255, 215, 0));
        Creditos_Label1.setText("Creditos");

        Creditos_Label2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Creditos_Label2.setForeground(new java.awt.Color(255, 215, 0));
        Creditos_Label2.setText("Profesor/es: Camila Lambertucci y Luciano Vera");

        Creditos_Label3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Creditos_Label3.setForeground(new java.awt.Color(255, 215, 0));
        Creditos_Label3.setText("Creador/es: Javier Meinard y Thiago Sambucetti");

        Creditos_Label4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Creditos_Label4.setForeground(new java.awt.Color(255, 215, 0));
        Creditos_Label4.setText("QA: Luciano Vera y Camila Lambertucci");

        Creditos_Label5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Creditos_Label5.setForeground(new java.awt.Color(255, 215, 0));
        Creditos_Label5.setText("Prototipado: Javier Meinard");

        Creditos_Label6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Creditos_Label6.setForeground(new java.awt.Color(255, 215, 0));
        Creditos_Label6.setText("Interfaz Grafica: Thiago Sambucetti");

        Creditos_Label7.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Creditos_Label7.setForeground(new java.awt.Color(255, 215, 0));
        Creditos_Label7.setText("Inspiracion/es: Preguntados y Quizizz");

        Creditos_Boton.setBackground(new java.awt.Color(0, 0, 0));
        Creditos_Boton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        Creditos_Boton.setForeground(new java.awt.Color(255, 215, 0));
        Creditos_Boton.setText("Salir");
        Creditos_Boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Creditos_BotonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Creditos_PanelLayout = new javax.swing.GroupLayout(Creditos_Panel);
        Creditos_Panel.setLayout(Creditos_PanelLayout);
        Creditos_PanelLayout.setHorizontalGroup(
            Creditos_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Creditos_PanelLayout.createSequentialGroup()
                .addGroup(Creditos_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Creditos_PanelLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(Creditos_Label1))
                    .addGroup(Creditos_PanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(Creditos_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Creditos_Label3)
                            .addComponent(Creditos_Label2)
                            .addComponent(Creditos_Label4)
                            .addComponent(Creditos_Label5)
                            .addComponent(Creditos_Label6)
                            .addComponent(Creditos_Label7)))
                    .addGroup(Creditos_PanelLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(Creditos_Boton)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        Creditos_PanelLayout.setVerticalGroup(
            Creditos_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Creditos_PanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Creditos_Label1)
                .addGap(73, 73, 73)
                .addComponent(Creditos_Label2)
                .addGap(60, 60, 60)
                .addComponent(Creditos_Label3)
                .addGap(78, 78, 78)
                .addComponent(Creditos_Label4)
                .addGap(73, 73, 73)
                .addComponent(Creditos_Label5)
                .addGap(67, 67, 67)
                .addComponent(Creditos_Label6)
                .addGap(74, 74, 74)
                .addComponent(Creditos_Label7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(Creditos_Boton)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Creditos_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Creditos_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Creditos_BotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Creditos_BotonMouseClicked
       Menu newFrame= new Menu();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Creditos_BotonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Creditos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Creditos_Boton;
    private javax.swing.JLabel Creditos_Label1;
    private javax.swing.JLabel Creditos_Label2;
    private javax.swing.JLabel Creditos_Label3;
    private javax.swing.JLabel Creditos_Label4;
    private javax.swing.JLabel Creditos_Label5;
    private javax.swing.JLabel Creditos_Label6;
    private javax.swing.JLabel Creditos_Label7;
    private javax.swing.JPanel Creditos_Panel;
    // End of variables declaration//GEN-END:variables
}
