package Menu;   



import Preguntas.Ingles1;
import Preguntas.Lengua1;
import Preguntas.Matematica1;
import Preguntas.CsSociales1;
import Preguntas.CsNaturales1;


public class Juego extends javax.swing.JFrame {

    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
        setLocationRelativeTo(null); /* Centra la ventana que se abre */
        setResizable(false); /* Le prohibe al usuario editar el tamaño*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Juego_Panel = new javax.swing.JPanel();
        Juego_Label = new javax.swing.JLabel();
        Juego_Boton1 = new javax.swing.JButton();
        Juego_Boton2 = new javax.swing.JButton();
        Juego_Boton3 = new javax.swing.JButton();
        Juego_Boton4 = new javax.swing.JButton();
        Juego_Boton5 = new javax.swing.JButton();
        Juego_Boton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego");

        Juego_Panel.setBackground(new java.awt.Color(0, 0, 0));

        Juego_Label.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Juego_Label.setForeground(new java.awt.Color(255, 215, 0));
        Juego_Label.setText("Seleccione una materia por favor");

        Juego_Boton1.setBackground(new java.awt.Color(0, 0, 0));
        Juego_Boton1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        Juego_Boton1.setForeground(new java.awt.Color(255, 215, 0));
        Juego_Boton1.setText("Ingles");
        Juego_Boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Juego_Boton1MouseClicked(evt);
            }
        });

        Juego_Boton2.setBackground(new java.awt.Color(0, 0, 0));
        Juego_Boton2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        Juego_Boton2.setForeground(new java.awt.Color(255, 215, 0));
        Juego_Boton2.setText("Lengua");
        Juego_Boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Juego_Boton2MouseClicked(evt);
            }
        });

        Juego_Boton3.setBackground(new java.awt.Color(0, 0, 0));
        Juego_Boton3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        Juego_Boton3.setForeground(new java.awt.Color(255, 215, 0));
        Juego_Boton3.setText("Matematica");
        Juego_Boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Juego_Boton3MouseClicked(evt);
            }
        });

        Juego_Boton4.setBackground(new java.awt.Color(0, 0, 0));
        Juego_Boton4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        Juego_Boton4.setForeground(new java.awt.Color(255, 215, 0));
        Juego_Boton4.setText("Cs. Sociales");
        Juego_Boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Juego_Boton4MouseClicked(evt);
            }
        });
        Juego_Boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Juego_Boton4ActionPerformed(evt);
            }
        });

        Juego_Boton5.setBackground(new java.awt.Color(0, 0, 0));
        Juego_Boton5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        Juego_Boton5.setForeground(new java.awt.Color(255, 215, 0));
        Juego_Boton5.setText("Cs. Naturales");
        Juego_Boton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Juego_Boton5MouseClicked(evt);
            }
        });

        Juego_Boton6.setBackground(new java.awt.Color(0, 0, 0));
        Juego_Boton6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        Juego_Boton6.setForeground(new java.awt.Color(255, 215, 0));
        Juego_Boton6.setText("Salir");
        Juego_Boton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Juego_Boton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Juego_PanelLayout = new javax.swing.GroupLayout(Juego_Panel);
        Juego_Panel.setLayout(Juego_PanelLayout);
        Juego_PanelLayout.setHorizontalGroup(
            Juego_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Juego_PanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(Juego_Label)
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Juego_PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Juego_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Juego_Boton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Juego_Boton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Juego_Boton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Juego_Boton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Juego_Boton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Juego_Boton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(191, 191, 191))
        );
        Juego_PanelLayout.setVerticalGroup(
            Juego_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Juego_PanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(Juego_Label)
                .addGap(180, 180, 180)
                .addComponent(Juego_Boton1)
                .addGap(43, 43, 43)
                .addComponent(Juego_Boton2)
                .addGap(38, 38, 38)
                .addComponent(Juego_Boton3)
                .addGap(43, 43, 43)
                .addComponent(Juego_Boton4)
                .addGap(40, 40, 40)
                .addComponent(Juego_Boton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(Juego_Boton6)
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Juego_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Juego_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Juego_Boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Juego_Boton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Juego_Boton4ActionPerformed

    private void Juego_Boton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Juego_Boton6MouseClicked
       Menu newFrame= new Menu();
       newFrame.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_Juego_Boton6MouseClicked

    private void Juego_Boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Juego_Boton1MouseClicked
       Ingles1 newFrame= new Ingles1();
       newFrame.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_Juego_Boton1MouseClicked

    private void Juego_Boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Juego_Boton2MouseClicked
       Lengua1 newFrame= new Lengua1();
       newFrame.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_Juego_Boton2MouseClicked

    private void Juego_Boton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Juego_Boton3MouseClicked
       Matematica1 newFrame= new Matematica1();
       newFrame.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_Juego_Boton3MouseClicked

    private void Juego_Boton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Juego_Boton4MouseClicked
       CsSociales1 newFrame= new CsSociales1();
       newFrame.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_Juego_Boton4MouseClicked

    private void Juego_Boton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Juego_Boton5MouseClicked
       CsNaturales1 newFrame= new CsNaturales1();
       newFrame.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_Juego_Boton5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Juego_Boton1;
    private javax.swing.JButton Juego_Boton2;
    private javax.swing.JButton Juego_Boton3;
    private javax.swing.JButton Juego_Boton4;
    private javax.swing.JButton Juego_Boton5;
    private javax.swing.JButton Juego_Boton6;
    private javax.swing.JLabel Juego_Label;
    private javax.swing.JPanel Juego_Panel;
    // End of variables declaration//GEN-END:variables
}
