package Menu;



import Menu.Juego;
import Menu.Creditos;
import Menu.Ayuda;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AlumnosET20
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null); /* Centra la ventana que se abre */
        setResizable(false); /* Le prohibe al usuario editar el tamaño*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu_Panel = new javax.swing.JPanel();
        Menu_Label1 = new javax.swing.JLabel();
        Menu_Label2 = new javax.swing.JLabel();
        Menu_Boton1 = new javax.swing.JButton();
        Menu_Boton3 = new javax.swing.JButton();
        Menu_Boton4 = new javax.swing.JButton();
        Menu_Boton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        Menu_Panel.setBackground(new java.awt.Color(0, 0, 0));

        Menu_Label1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Menu_Label1.setForeground(new java.awt.Color(255, 215, 0));
        Menu_Label1.setText("Inicio");
        Menu_Label1.setToolTipText("");
        Menu_Label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Menu_Label1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Menu_Label2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Primariados-Logo.png"))); // NOI18N

        Menu_Boton1.setBackground(new java.awt.Color(0, 0, 0));
        Menu_Boton1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        Menu_Boton1.setForeground(new java.awt.Color(255, 215, 0));
        Menu_Boton1.setText("Jugar");
        Menu_Boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_Boton1MouseClicked(evt);
            }
        });

        Menu_Boton3.setBackground(new java.awt.Color(0, 0, 0));
        Menu_Boton3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        Menu_Boton3.setForeground(new java.awt.Color(255, 215, 0));
        Menu_Boton3.setText("Ayuda");
        Menu_Boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_Boton3MouseClicked(evt);
            }
        });
        Menu_Boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Boton3ActionPerformed(evt);
            }
        });

        Menu_Boton4.setBackground(new java.awt.Color(0, 0, 0));
        Menu_Boton4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        Menu_Boton4.setForeground(new java.awt.Color(255, 215, 0));
        Menu_Boton4.setText("Creditos");
        Menu_Boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_Boton4MouseClicked(evt);
            }
        });

        Menu_Boton5.setBackground(new java.awt.Color(0, 0, 0));
        Menu_Boton5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        Menu_Boton5.setForeground(new java.awt.Color(255, 215, 0));
        Menu_Boton5.setText("Salir");
        Menu_Boton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_Boton5MouseClicked(evt);
            }
        });
        Menu_Boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Boton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Menu_PanelLayout = new javax.swing.GroupLayout(Menu_Panel);
        Menu_Panel.setLayout(Menu_PanelLayout);
        Menu_PanelLayout.setHorizontalGroup(
            Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_PanelLayout.createSequentialGroup()
                .addGroup(Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Menu_PanelLayout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addGroup(Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Menu_Boton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Menu_Boton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Menu_Boton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Menu_Boton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Menu_Label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(Menu_PanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(Menu_Label2)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        Menu_PanelLayout.setVerticalGroup(
            Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_PanelLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(Menu_Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(Menu_Label1)
                .addGap(81, 81, 81)
                .addComponent(Menu_Boton1)
                .addGap(66, 66, 66)
                .addComponent(Menu_Boton3)
                .addGap(63, 63, 63)
                .addComponent(Menu_Boton4)
                .addGap(62, 62, 62)
                .addComponent(Menu_Boton5)
                .addGap(135, 135, 135))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_Boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Boton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu_Boton3ActionPerformed

    private void Menu_Boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Boton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu_Boton5ActionPerformed

    private void Menu_Boton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_Boton3MouseClicked
        Ayuda newFrame= new Ayuda();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Menu_Boton3MouseClicked

    private void Menu_Boton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_Boton4MouseClicked
        Creditos newFrame= new Creditos();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Menu_Boton4MouseClicked

    private void Menu_Boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_Boton1MouseClicked
        Juego newFrame= new Juego(); 
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Menu_Boton1MouseClicked

    private void Menu_Boton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_Boton5MouseClicked
        System.exit(WIDTH); /* Cierra el programa */
    }//GEN-LAST:event_Menu_Boton5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
                
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Menu_Boton1;
    private javax.swing.JButton Menu_Boton3;
    private javax.swing.JButton Menu_Boton4;
    private javax.swing.JButton Menu_Boton5;
    private javax.swing.JLabel Menu_Label1;
    private javax.swing.JLabel Menu_Label2;
    private javax.swing.JPanel Menu_Panel;
    // End of variables declaration//GEN-END:variables
}
