/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Preguntas;
import java.awt.Color;

/**
 *
 * @author ET20 - Alumno
 */
public class CsNaturales1 extends javax.swing.JFrame {

    /**
     * Creates new form CsNaturales1
     */
    public CsNaturales1() {
        initComponents();
        setLocationRelativeTo(null); /* Centra la ventana que se abre */
        setResizable(false); /* Le prohibe al usuario editar el tamaño*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CsNaturales1_Panel = new javax.swing.JPanel();
        CsNaturales1_Label1 = new javax.swing.JLabel();
        CsNaturales1_Label2 = new javax.swing.JLabel();
        CsNaturales1_Boton1 = new javax.swing.JButton();
        CsNaturales1_Boton2 = new javax.swing.JButton();
        CsNaturales1_Boton3 = new javax.swing.JButton();
        CsNaturales1_Boton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CsNaturales1_Panel.setBackground(new java.awt.Color(0, 0, 0));

        CsNaturales1_Label1.setBackground(new java.awt.Color(0, 0, 0));
        CsNaturales1_Label1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        CsNaturales1_Label1.setForeground(new java.awt.Color(255, 215, 0));
        CsNaturales1_Label1.setText("Cs Naturales");

        CsNaturales1_Label2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        CsNaturales1_Label2.setForeground(new java.awt.Color(255, 215, 0));
        CsNaturales1_Label2.setText("¿Cuántos huesos tiene el cuerpo humano?");

        CsNaturales1_Boton1.setBackground(new java.awt.Color(0, 0, 0));
        CsNaturales1_Boton1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        CsNaturales1_Boton1.setForeground(new java.awt.Color(255, 215, 0));
        CsNaturales1_Boton1.setText("200");
        CsNaturales1_Boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CsNaturales1_Boton1MouseClicked(evt);
            }
        });

        CsNaturales1_Boton2.setBackground(new java.awt.Color(0, 0, 0));
        CsNaturales1_Boton2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        CsNaturales1_Boton2.setForeground(new java.awt.Color(255, 215, 0));
        CsNaturales1_Boton2.setText("180");
        CsNaturales1_Boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CsNaturales1_Boton2MouseClicked(evt);
            }
        });

        CsNaturales1_Boton3.setBackground(new java.awt.Color(0, 0, 0));
        CsNaturales1_Boton3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        CsNaturales1_Boton3.setForeground(new java.awt.Color(255, 215, 0));
        CsNaturales1_Boton3.setText("210");
        CsNaturales1_Boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CsNaturales1_Boton3MouseClicked(evt);
            }
        });

        CsNaturales1_Boton4.setBackground(new java.awt.Color(0, 0, 0));
        CsNaturales1_Boton4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        CsNaturales1_Boton4.setForeground(new java.awt.Color(255, 215, 0));
        CsNaturales1_Boton4.setText("206");
        CsNaturales1_Boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CsNaturales1_Boton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CsNaturales1_PanelLayout = new javax.swing.GroupLayout(CsNaturales1_Panel);
        CsNaturales1_Panel.setLayout(CsNaturales1_PanelLayout);
        CsNaturales1_PanelLayout.setHorizontalGroup(
            CsNaturales1_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CsNaturales1_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CsNaturales1_Label1)
                .addGap(174, 174, 174))
            .addGroup(CsNaturales1_PanelLayout.createSequentialGroup()
                .addGroup(CsNaturales1_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CsNaturales1_PanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(CsNaturales1_Label2))
                    .addGroup(CsNaturales1_PanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(CsNaturales1_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CsNaturales1_Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CsNaturales1_Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CsNaturales1_Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CsNaturales1_Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        CsNaturales1_PanelLayout.setVerticalGroup(
            CsNaturales1_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CsNaturales1_PanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(CsNaturales1_Label1)
                .addGap(45, 45, 45)
                .addComponent(CsNaturales1_Label2)
                .addGap(68, 68, 68)
                .addComponent(CsNaturales1_Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(CsNaturales1_Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(CsNaturales1_Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(CsNaturales1_Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(352, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CsNaturales1_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CsNaturales1_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CsNaturales1_Boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CsNaturales1_Boton1MouseClicked
        // TODO add your handling code here:
        CsNaturales1_Boton1.setBackground(Color.RED);
        CsNaturales1_Boton1.setForeground(Color.WHITE);
        CsNaturales1_Boton2.setBackground(Color.RED);
        CsNaturales1_Boton2.setForeground(Color.WHITE);
        CsNaturales1_Boton3.setBackground(Color.RED);
        CsNaturales1_Boton3.setForeground(Color.WHITE);
        CsNaturales1_Boton4.setBackground(Color.GREEN);
        CsNaturales1_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_CsNaturales1_Boton1MouseClicked

    private void CsNaturales1_Boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CsNaturales1_Boton2MouseClicked
        // TODO add your handling code here:
        CsNaturales1_Boton1.setBackground(Color.RED);
        CsNaturales1_Boton1.setForeground(Color.WHITE);
        CsNaturales1_Boton2.setBackground(Color.RED);
        CsNaturales1_Boton2.setForeground(Color.WHITE);
        CsNaturales1_Boton3.setBackground(Color.RED);
        CsNaturales1_Boton3.setForeground(Color.WHITE);
        CsNaturales1_Boton4.setBackground(Color.GREEN);
        CsNaturales1_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_CsNaturales1_Boton2MouseClicked

    private void CsNaturales1_Boton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CsNaturales1_Boton3MouseClicked
        // TODO add your handling code here:
        CsNaturales1_Boton1.setBackground(Color.RED);
        CsNaturales1_Boton1.setForeground(Color.WHITE);
        CsNaturales1_Boton2.setBackground(Color.RED);
        CsNaturales1_Boton2.setForeground(Color.WHITE);
        CsNaturales1_Boton3.setBackground(Color.RED);
        CsNaturales1_Boton3.setForeground(Color.WHITE);
        CsNaturales1_Boton4.setBackground(Color.GREEN);
        CsNaturales1_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_CsNaturales1_Boton3MouseClicked

    private void CsNaturales1_Boton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CsNaturales1_Boton4MouseClicked
        CsNaturales2 newFrame = new CsNaturales2();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CsNaturales1_Boton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CsNaturales1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CsNaturales1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CsNaturales1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CsNaturales1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CsNaturales1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CsNaturales1_Boton1;
    private javax.swing.JButton CsNaturales1_Boton2;
    private javax.swing.JButton CsNaturales1_Boton3;
    private javax.swing.JButton CsNaturales1_Boton4;
    private javax.swing.JLabel CsNaturales1_Label1;
    private javax.swing.JLabel CsNaturales1_Label2;
    private javax.swing.JPanel CsNaturales1_Panel;
    // End of variables declaration//GEN-END:variables
}
