/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Preguntas;

import java.awt.Color;

/**
 *
 * @author ET20 - Alumno
 */
public class CsNaturales4 extends javax.swing.JFrame {

    /**
     * Creates new form CsNaturales4
     */
    public CsNaturales4() {
        initComponents();
        setLocationRelativeTo(null); /* Centra la ventana que se abre */
        setResizable(false); /* Le prohibe al usuario editar el tamaño*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CsNaturales4_Panel = new javax.swing.JPanel();
        CsNaturales4_Label1 = new javax.swing.JLabel();
        CsNaturales4_Label2 = new javax.swing.JLabel();
        CsNaturales4_Boton1 = new javax.swing.JButton();
        CsNaturales4_Boton2 = new javax.swing.JButton();
        CsNaturales4_Boton3 = new javax.swing.JButton();
        CsNaturales4_Boton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CsNaturales4_Panel.setBackground(new java.awt.Color(0, 0, 0));

        CsNaturales4_Label1.setBackground(new java.awt.Color(0, 0, 0));
        CsNaturales4_Label1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        CsNaturales4_Label1.setForeground(new java.awt.Color(255, 215, 0));
        CsNaturales4_Label1.setText("Cs Naturales");

        CsNaturales4_Label2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        CsNaturales4_Label2.setForeground(new java.awt.Color(255, 215, 0));
        CsNaturales4_Label2.setText("¿Cuáles son los 3 estados de la materia?");

        CsNaturales4_Boton1.setBackground(new java.awt.Color(0, 0, 0));
        CsNaturales4_Boton1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        CsNaturales4_Boton1.setForeground(new java.awt.Color(255, 215, 0));
        CsNaturales4_Boton1.setText("Sólido, líquido y gaseoso");
        CsNaturales4_Boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CsNaturales4_Boton1MouseClicked(evt);
            }
        });

        CsNaturales4_Boton2.setBackground(new java.awt.Color(0, 0, 0));
        CsNaturales4_Boton2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        CsNaturales4_Boton2.setForeground(new java.awt.Color(255, 215, 0));
        CsNaturales4_Boton2.setText("Vivo, en descomposición e inerte");
        CsNaturales4_Boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CsNaturales4_Boton2MouseClicked(evt);
            }
        });

        CsNaturales4_Boton3.setBackground(new java.awt.Color(0, 0, 0));
        CsNaturales4_Boton3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        CsNaturales4_Boton3.setForeground(new java.awt.Color(255, 215, 0));
        CsNaturales4_Boton3.setText("Sólido, líquido y plasmático");
        CsNaturales4_Boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CsNaturales4_Boton3MouseClicked(evt);
            }
        });

        CsNaturales4_Boton4.setBackground(new java.awt.Color(0, 0, 0));
        CsNaturales4_Boton4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        CsNaturales4_Boton4.setForeground(new java.awt.Color(255, 215, 0));
        CsNaturales4_Boton4.setText("No son 3");
        CsNaturales4_Boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CsNaturales4_Boton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CsNaturales4_PanelLayout = new javax.swing.GroupLayout(CsNaturales4_Panel);
        CsNaturales4_Panel.setLayout(CsNaturales4_PanelLayout);
        CsNaturales4_PanelLayout.setHorizontalGroup(
            CsNaturales4_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CsNaturales4_PanelLayout.createSequentialGroup()
                .addGroup(CsNaturales4_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CsNaturales4_PanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(CsNaturales4_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CsNaturales4_Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CsNaturales4_Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CsNaturales4_Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CsNaturales4_Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CsNaturales4_PanelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(CsNaturales4_Label2))))
                    .addGroup(CsNaturales4_PanelLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(CsNaturales4_Label1)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        CsNaturales4_PanelLayout.setVerticalGroup(
            CsNaturales4_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CsNaturales4_PanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(CsNaturales4_Label1)
                .addGap(57, 57, 57)
                .addComponent(CsNaturales4_Label2)
                .addGap(76, 76, 76)
                .addComponent(CsNaturales4_Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(CsNaturales4_Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(CsNaturales4_Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(CsNaturales4_Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(322, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CsNaturales4_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CsNaturales4_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CsNaturales4_Boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CsNaturales4_Boton1MouseClicked
        // TODO add your handling code here:
        CsNaturales5 newFrame = new CsNaturales5();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CsNaturales4_Boton1MouseClicked

    private void CsNaturales4_Boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CsNaturales4_Boton2MouseClicked
        // TODO add your handling code here:
        CsNaturales4_Boton1.setBackground(Color.GREEN);
        CsNaturales4_Boton1.setForeground(Color.WHITE);
        CsNaturales4_Boton2.setBackground(Color.RED);
        CsNaturales4_Boton2.setForeground(Color.WHITE);
        CsNaturales4_Boton3.setBackground(Color.RED);
        CsNaturales4_Boton3.setForeground(Color.WHITE);
        CsNaturales4_Boton4.setBackground(Color.RED);
        CsNaturales4_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_CsNaturales4_Boton2MouseClicked

    private void CsNaturales4_Boton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CsNaturales4_Boton3MouseClicked
        // TODO add your handling code here:
        CsNaturales4_Boton1.setBackground(Color.GREEN);
        CsNaturales4_Boton1.setForeground(Color.WHITE);
        CsNaturales4_Boton2.setBackground(Color.RED);
        CsNaturales4_Boton2.setForeground(Color.WHITE);
        CsNaturales4_Boton3.setBackground(Color.RED);
        CsNaturales4_Boton3.setForeground(Color.WHITE);
        CsNaturales4_Boton4.setBackground(Color.RED);
        CsNaturales4_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_CsNaturales4_Boton3MouseClicked

    private void CsNaturales4_Boton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CsNaturales4_Boton4MouseClicked
        // TODO add your handling code here:
        CsNaturales4_Boton1.setBackground(Color.GREEN);
        CsNaturales4_Boton1.setForeground(Color.WHITE);
        CsNaturales4_Boton2.setBackground(Color.RED);
        CsNaturales4_Boton2.setForeground(Color.WHITE);
        CsNaturales4_Boton3.setBackground(Color.RED);
        CsNaturales4_Boton3.setForeground(Color.WHITE);
        CsNaturales4_Boton4.setBackground(Color.RED);
        CsNaturales4_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_CsNaturales4_Boton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CsNaturales4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CsNaturales4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CsNaturales4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CsNaturales4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CsNaturales4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CsNaturales4_Boton1;
    private javax.swing.JButton CsNaturales4_Boton2;
    private javax.swing.JButton CsNaturales4_Boton3;
    private javax.swing.JButton CsNaturales4_Boton4;
    private javax.swing.JLabel CsNaturales4_Label1;
    private javax.swing.JLabel CsNaturales4_Label2;
    private javax.swing.JPanel CsNaturales4_Panel;
    // End of variables declaration//GEN-END:variables
}
