/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Preguntas;

import java.awt.Color;

/**
 *
 * @author ET20 - Alumno
 */
public class CsSociales4 extends javax.swing.JFrame {

    /**
     * Creates new form CsSociales4
     */
    public CsSociales4() {
        initComponents();
        setLocationRelativeTo(null); /* Centra la ventana que se abre */
        setResizable(false); /* Le prohibe al usuario editar el tamaño*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CsSociales4_Panel = new javax.swing.JPanel();
        CsSociales4_Label1 = new javax.swing.JLabel();
        CsSociales4_Label2 = new javax.swing.JLabel();
        CsSociales4_Boton1 = new javax.swing.JButton();
        CsSociales4_Boton2 = new javax.swing.JButton();
        CsSociales4_Boton3 = new javax.swing.JButton();
        CsSociales4_Boton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CsSociales4_Panel.setBackground(new java.awt.Color(0, 0, 0));

        CsSociales4_Label1.setBackground(new java.awt.Color(0, 0, 0));
        CsSociales4_Label1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        CsSociales4_Label1.setForeground(new java.awt.Color(255, 215, 0));
        CsSociales4_Label1.setText("Cs Sociales");

        CsSociales4_Label2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        CsSociales4_Label2.setForeground(new java.awt.Color(255, 215, 0));
        CsSociales4_Label2.setText("¿En qué etapas se divide la prehistoria?");

        CsSociales4_Boton1.setBackground(new java.awt.Color(0, 0, 0));
        CsSociales4_Boton1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        CsSociales4_Boton1.setForeground(new java.awt.Color(255, 215, 0));
        CsSociales4_Boton1.setText("Paleolítico, Neolítico y Edad de los Metales");
        CsSociales4_Boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CsSociales4_Boton1MouseClicked(evt);
            }
        });

        CsSociales4_Boton2.setBackground(new java.awt.Color(0, 0, 0));
        CsSociales4_Boton2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        CsSociales4_Boton2.setForeground(new java.awt.Color(255, 215, 0));
        CsSociales4_Boton2.setText("Paleolítico y Edad de Piedra");
        CsSociales4_Boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CsSociales4_Boton2MouseClicked(evt);
            }
        });

        CsSociales4_Boton3.setBackground(new java.awt.Color(0, 0, 0));
        CsSociales4_Boton3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        CsSociales4_Boton3.setForeground(new java.awt.Color(255, 215, 0));
        CsSociales4_Boton3.setText("Pre escritura y post escritura");
        CsSociales4_Boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CsSociales4_Boton3MouseClicked(evt);
            }
        });

        CsSociales4_Boton4.setBackground(new java.awt.Color(0, 0, 0));
        CsSociales4_Boton4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        CsSociales4_Boton4.setForeground(new java.awt.Color(255, 215, 0));
        CsSociales4_Boton4.setText("Paleolítico y Neolítico");
        CsSociales4_Boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CsSociales4_Boton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CsSociales4_PanelLayout = new javax.swing.GroupLayout(CsSociales4_Panel);
        CsSociales4_Panel.setLayout(CsSociales4_PanelLayout);
        CsSociales4_PanelLayout.setHorizontalGroup(
            CsSociales4_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CsSociales4_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CsSociales4_Label1)
                .addGap(184, 184, 184))
            .addGroup(CsSociales4_PanelLayout.createSequentialGroup()
                .addGroup(CsSociales4_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CsSociales4_PanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(CsSociales4_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CsSociales4_Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CsSociales4_Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CsSociales4_Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CsSociales4_Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CsSociales4_PanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(CsSociales4_Label2)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        CsSociales4_PanelLayout.setVerticalGroup(
            CsSociales4_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CsSociales4_PanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(CsSociales4_Label1)
                .addGap(61, 61, 61)
                .addComponent(CsSociales4_Label2)
                .addGap(63, 63, 63)
                .addComponent(CsSociales4_Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(CsSociales4_Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(CsSociales4_Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(CsSociales4_Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(329, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CsSociales4_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CsSociales4_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CsSociales4_Boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CsSociales4_Boton1MouseClicked
        CsSociales4_Boton1.setBackground(Color.RED);
        CsSociales4_Boton1.setForeground(Color.WHITE);
        CsSociales4_Boton2.setBackground(Color.RED);
        CsSociales4_Boton2.setForeground(Color.WHITE);
        CsSociales4_Boton3.setBackground(Color.RED);
        CsSociales4_Boton3.setForeground(Color.WHITE);
        CsSociales4_Boton4.setBackground(Color.GREEN);
        CsSociales4_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_CsSociales4_Boton1MouseClicked

    private void CsSociales4_Boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CsSociales4_Boton2MouseClicked
        CsSociales4_Boton1.setBackground(Color.RED);
        CsSociales4_Boton1.setForeground(Color.WHITE);
        CsSociales4_Boton2.setBackground(Color.RED);
        CsSociales4_Boton2.setForeground(Color.WHITE);
        CsSociales4_Boton3.setBackground(Color.RED);
        CsSociales4_Boton3.setForeground(Color.WHITE);
        CsSociales4_Boton4.setBackground(Color.GREEN);
        CsSociales4_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_CsSociales4_Boton2MouseClicked

    private void CsSociales4_Boton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CsSociales4_Boton3MouseClicked
        CsSociales4_Boton1.setBackground(Color.RED);
        CsSociales4_Boton1.setForeground(Color.WHITE);
        CsSociales4_Boton2.setBackground(Color.RED);
        CsSociales4_Boton2.setForeground(Color.WHITE);
        CsSociales4_Boton3.setBackground(Color.RED);
        CsSociales4_Boton3.setForeground(Color.WHITE);
        CsSociales4_Boton4.setBackground(Color.GREEN);
        CsSociales4_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_CsSociales4_Boton3MouseClicked

    private void CsSociales4_Boton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CsSociales4_Boton4MouseClicked
        CsSociales5 newFrame = new CsSociales5();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CsSociales4_Boton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CsSociales4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CsSociales4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CsSociales4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CsSociales4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CsSociales4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CsSociales4_Boton1;
    private javax.swing.JButton CsSociales4_Boton2;
    private javax.swing.JButton CsSociales4_Boton3;
    private javax.swing.JButton CsSociales4_Boton4;
    private javax.swing.JLabel CsSociales4_Label1;
    private javax.swing.JLabel CsSociales4_Label2;
    private javax.swing.JPanel CsSociales4_Panel;
    // End of variables declaration//GEN-END:variables
}
