/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Preguntas;

import java.awt.Color;

/**
 *
 * @author ET20 - Alumno
 */
public class CsSociales2 extends javax.swing.JFrame {

    /**
     * Creates new form CsSociales2
     */
    public CsSociales2() {
        initComponents();
        setLocationRelativeTo(null); /* Centra la ventana que se abre */
        setResizable(false); /* Le prohibe al usuario editar el tamaño*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CsSociales2_Panel = new javax.swing.JPanel();
        CsSociales2_Label1 = new javax.swing.JLabel();
        CsSociales2_Label2 = new javax.swing.JLabel();
        CsSociales2_Boton1 = new javax.swing.JButton();
        CsSociales2_Boton2 = new javax.swing.JButton();
        CsSociales2_Boton3 = new javax.swing.JButton();
        CsSociales2_Boton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CsSociales2_Panel.setBackground(new java.awt.Color(0, 0, 0));

        CsSociales2_Label1.setBackground(new java.awt.Color(0, 0, 0));
        CsSociales2_Label1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        CsSociales2_Label1.setForeground(new java.awt.Color(255, 215, 0));
        CsSociales2_Label1.setText("Cs Sociales");

        CsSociales2_Label2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        CsSociales2_Label2.setForeground(new java.awt.Color(255, 215, 0));
        CsSociales2_Label2.setText("¿Cómo se llama la formación conjunta de varias montañas?");

        CsSociales2_Boton1.setBackground(new java.awt.Color(0, 0, 0));
        CsSociales2_Boton1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        CsSociales2_Boton1.setForeground(new java.awt.Color(255, 215, 0));
        CsSociales2_Boton1.setText("Sierra");
        CsSociales2_Boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CsSociales2_Boton1MouseClicked(evt);
            }
        });

        CsSociales2_Boton2.setBackground(new java.awt.Color(0, 0, 0));
        CsSociales2_Boton2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        CsSociales2_Boton2.setForeground(new java.awt.Color(255, 215, 0));
        CsSociales2_Boton2.setText("Cordillera");
        CsSociales2_Boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CsSociales2_Boton2MouseClicked(evt);
            }
        });

        CsSociales2_Boton3.setBackground(new java.awt.Color(0, 0, 0));
        CsSociales2_Boton3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        CsSociales2_Boton3.setForeground(new java.awt.Color(255, 215, 0));
        CsSociales2_Boton3.setText("Altiplano");
        CsSociales2_Boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CsSociales2_Boton3MouseClicked(evt);
            }
        });

        CsSociales2_Boton4.setBackground(new java.awt.Color(0, 0, 0));
        CsSociales2_Boton4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        CsSociales2_Boton4.setForeground(new java.awt.Color(255, 215, 0));
        CsSociales2_Boton4.setText("Valle");
        CsSociales2_Boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CsSociales2_Boton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CsSociales2_PanelLayout = new javax.swing.GroupLayout(CsSociales2_Panel);
        CsSociales2_Panel.setLayout(CsSociales2_PanelLayout);
        CsSociales2_PanelLayout.setHorizontalGroup(
            CsSociales2_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CsSociales2_PanelLayout.createSequentialGroup()
                .addGroup(CsSociales2_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CsSociales2_PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CsSociales2_Label2))
                    .addGroup(CsSociales2_PanelLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(CsSociales2_Label1))
                    .addGroup(CsSociales2_PanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(CsSociales2_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CsSociales2_Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CsSociales2_Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CsSociales2_Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CsSociales2_Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        CsSociales2_PanelLayout.setVerticalGroup(
            CsSociales2_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CsSociales2_PanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(CsSociales2_Label1)
                .addGap(53, 53, 53)
                .addComponent(CsSociales2_Label2)
                .addGap(70, 70, 70)
                .addComponent(CsSociales2_Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(CsSociales2_Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(CsSociales2_Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(CsSociales2_Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(350, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CsSociales2_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CsSociales2_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CsSociales2_Boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CsSociales2_Boton1MouseClicked
        CsSociales2_Boton1.setBackground(Color.RED);
        CsSociales2_Boton1.setForeground(Color.WHITE);
        CsSociales2_Boton2.setBackground(Color.GREEN);
        CsSociales2_Boton2.setForeground(Color.WHITE);
        CsSociales2_Boton3.setBackground(Color.RED);
        CsSociales2_Boton3.setForeground(Color.WHITE);
        CsSociales2_Boton4.setBackground(Color.RED);
        CsSociales2_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_CsSociales2_Boton1MouseClicked

    private void CsSociales2_Boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CsSociales2_Boton2MouseClicked
        CsSociales3 newFrame = new CsSociales3();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CsSociales2_Boton2MouseClicked

    private void CsSociales2_Boton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CsSociales2_Boton3MouseClicked
        CsSociales2_Boton1.setBackground(Color.RED);
        CsSociales2_Boton1.setForeground(Color.WHITE);
        CsSociales2_Boton2.setBackground(Color.GREEN);
        CsSociales2_Boton2.setForeground(Color.WHITE);
        CsSociales2_Boton3.setBackground(Color.RED);
        CsSociales2_Boton3.setForeground(Color.WHITE);
        CsSociales2_Boton4.setBackground(Color.RED);
        CsSociales2_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_CsSociales2_Boton3MouseClicked

    private void CsSociales2_Boton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CsSociales2_Boton4MouseClicked
        CsSociales2_Boton1.setBackground(Color.RED);
        CsSociales2_Boton1.setForeground(Color.WHITE);
        CsSociales2_Boton2.setBackground(Color.GREEN);
        CsSociales2_Boton2.setForeground(Color.WHITE);
        CsSociales2_Boton3.setBackground(Color.RED);
        CsSociales2_Boton3.setForeground(Color.WHITE);
        CsSociales2_Boton4.setBackground(Color.RED);
        CsSociales2_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_CsSociales2_Boton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CsSociales2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CsSociales2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CsSociales2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CsSociales2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CsSociales2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CsSociales2_Boton1;
    private javax.swing.JButton CsSociales2_Boton2;
    private javax.swing.JButton CsSociales2_Boton3;
    private javax.swing.JButton CsSociales2_Boton4;
    private javax.swing.JLabel CsSociales2_Label1;
    private javax.swing.JLabel CsSociales2_Label2;
    private javax.swing.JPanel CsSociales2_Panel;
    // End of variables declaration//GEN-END:variables
}
