/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Preguntas;

import Menu.Juego;
import java.awt.Color;

/**
 *
 * @author ET20 - Alumno
 */
public class CsSociales5 extends javax.swing.JFrame {

    /**
     * Creates new form CsSociales5
     */
    public CsSociales5() {
        initComponents();
        setLocationRelativeTo(null); /* Centra la ventana que se abre */
        setResizable(false); /* Le prohibe al usuario editar el tamaño*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CsSociales5_Panel = new javax.swing.JPanel();
        CsSociales5_Label1 = new javax.swing.JLabel();
        CsSociales5_Label2 = new javax.swing.JLabel();
        CsSociales5_Boton1 = new javax.swing.JButton();
        CsSociales5_Boton2 = new javax.swing.JButton();
        CsSociales5_Boton3 = new javax.swing.JButton();
        CsSociales5_Boton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CsSociales5_Panel.setBackground(new java.awt.Color(0, 0, 0));

        CsSociales5_Label1.setBackground(new java.awt.Color(0, 0, 0));
        CsSociales5_Label1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        CsSociales5_Label1.setForeground(new java.awt.Color(255, 215, 0));
        CsSociales5_Label1.setText("Cs Sociales");

        CsSociales5_Label2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        CsSociales5_Label2.setForeground(new java.awt.Color(255, 215, 0));
        CsSociales5_Label2.setText("¿Qué civilización antigua dio origen a la democracia?");

        CsSociales5_Boton1.setBackground(new java.awt.Color(0, 0, 0));
        CsSociales5_Boton1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        CsSociales5_Boton1.setForeground(new java.awt.Color(255, 215, 0));
        CsSociales5_Boton1.setText("Grecia");
        CsSociales5_Boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CsSociales5_Boton1MouseClicked(evt);
            }
        });
        CsSociales5_Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CsSociales5_Boton1ActionPerformed(evt);
            }
        });

        CsSociales5_Boton2.setBackground(new java.awt.Color(0, 0, 0));
        CsSociales5_Boton2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        CsSociales5_Boton2.setForeground(new java.awt.Color(255, 215, 0));
        CsSociales5_Boton2.setText("Roma");
        CsSociales5_Boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CsSociales5_Boton2MouseClicked(evt);
            }
        });
        CsSociales5_Boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CsSociales5_Boton2ActionPerformed(evt);
            }
        });

        CsSociales5_Boton3.setBackground(new java.awt.Color(0, 0, 0));
        CsSociales5_Boton3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        CsSociales5_Boton3.setForeground(new java.awt.Color(255, 215, 0));
        CsSociales5_Boton3.setText("Egipto");
        CsSociales5_Boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CsSociales5_Boton3MouseClicked(evt);
            }
        });
        CsSociales5_Boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CsSociales5_Boton3ActionPerformed(evt);
            }
        });

        CsSociales5_Boton4.setBackground(new java.awt.Color(0, 0, 0));
        CsSociales5_Boton4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        CsSociales5_Boton4.setForeground(new java.awt.Color(255, 215, 0));
        CsSociales5_Boton4.setText("India");
        CsSociales5_Boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CsSociales5_Boton4MouseClicked(evt);
            }
        });
        CsSociales5_Boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CsSociales5_Boton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CsSociales5_PanelLayout = new javax.swing.GroupLayout(CsSociales5_Panel);
        CsSociales5_Panel.setLayout(CsSociales5_PanelLayout);
        CsSociales5_PanelLayout.setHorizontalGroup(
            CsSociales5_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CsSociales5_PanelLayout.createSequentialGroup()
                .addGroup(CsSociales5_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CsSociales5_PanelLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(CsSociales5_Label1))
                    .addGroup(CsSociales5_PanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(CsSociales5_Label2))
                    .addGroup(CsSociales5_PanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(CsSociales5_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CsSociales5_Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CsSociales5_Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CsSociales5_Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CsSociales5_Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        CsSociales5_PanelLayout.setVerticalGroup(
            CsSociales5_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CsSociales5_PanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(CsSociales5_Label1)
                .addGap(47, 47, 47)
                .addComponent(CsSociales5_Label2)
                .addGap(72, 72, 72)
                .addComponent(CsSociales5_Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(CsSociales5_Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(CsSociales5_Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(CsSociales5_Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(339, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CsSociales5_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CsSociales5_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CsSociales5_Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CsSociales5_Boton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CsSociales5_Boton1ActionPerformed

    private void CsSociales5_Boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CsSociales5_Boton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CsSociales5_Boton2ActionPerformed

    private void CsSociales5_Boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CsSociales5_Boton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CsSociales5_Boton3ActionPerformed

    private void CsSociales5_Boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CsSociales5_Boton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CsSociales5_Boton4ActionPerformed

    private void CsSociales5_Boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CsSociales5_Boton1MouseClicked
        Juego newFrame= new Juego(); 
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CsSociales5_Boton1MouseClicked

    private void CsSociales5_Boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CsSociales5_Boton2MouseClicked
        CsSociales5_Boton1.setBackground(Color.GREEN);
        CsSociales5_Boton1.setForeground(Color.WHITE);
        CsSociales5_Boton2.setBackground(Color.RED);
        CsSociales5_Boton2.setForeground(Color.WHITE);
        CsSociales5_Boton3.setBackground(Color.RED);
        CsSociales5_Boton3.setForeground(Color.WHITE);
        CsSociales5_Boton4.setBackground(Color.RED);
        CsSociales5_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_CsSociales5_Boton2MouseClicked

    private void CsSociales5_Boton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CsSociales5_Boton3MouseClicked
        CsSociales5_Boton1.setBackground(Color.GREEN);
        CsSociales5_Boton1.setForeground(Color.WHITE);
        CsSociales5_Boton2.setBackground(Color.RED);
        CsSociales5_Boton2.setForeground(Color.WHITE);
        CsSociales5_Boton3.setBackground(Color.RED);
        CsSociales5_Boton3.setForeground(Color.WHITE);
        CsSociales5_Boton4.setBackground(Color.RED);
        CsSociales5_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_CsSociales5_Boton3MouseClicked

    private void CsSociales5_Boton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CsSociales5_Boton4MouseClicked
        CsSociales5_Boton1.setBackground(Color.GREEN);
        CsSociales5_Boton1.setForeground(Color.WHITE);
        CsSociales5_Boton2.setBackground(Color.RED);
        CsSociales5_Boton2.setForeground(Color.WHITE);
        CsSociales5_Boton3.setBackground(Color.RED);
        CsSociales5_Boton3.setForeground(Color.WHITE);
        CsSociales5_Boton4.setBackground(Color.RED);
        CsSociales5_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_CsSociales5_Boton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CsSociales5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CsSociales5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CsSociales5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CsSociales5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CsSociales5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CsSociales5_Boton1;
    private javax.swing.JButton CsSociales5_Boton2;
    private javax.swing.JButton CsSociales5_Boton3;
    private javax.swing.JButton CsSociales5_Boton4;
    private javax.swing.JLabel CsSociales5_Label1;
    private javax.swing.JLabel CsSociales5_Label2;
    private javax.swing.JPanel CsSociales5_Panel;
    // End of variables declaration//GEN-END:variables
}
