package Preguntas;

import java.awt.Color;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ET20 - Alumno
 */
public class Ingles1 extends javax.swing.JFrame {

    /**
     * Creates new form Ingles1
     */
    public Ingles1() {
        initComponents();
        setLocationRelativeTo(null); /* Centra la ventana que se abre */
        setResizable(false); /* Le prohibe al usuario editar el tamaño*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ingles1_Panel = new javax.swing.JPanel();
        Ingles1_Label1 = new javax.swing.JLabel();
        Ingles1_Label2 = new javax.swing.JLabel();
        Ingles1_Boton1 = new javax.swing.JButton();
        Ingles1_Boton2 = new javax.swing.JButton();
        Ingles1_Boton3 = new javax.swing.JButton();
        Ingles1_Boton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Ingles1_Panel.setBackground(new java.awt.Color(0, 0, 0));

        Ingles1_Label1.setBackground(new java.awt.Color(0, 0, 0));
        Ingles1_Label1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Ingles1_Label1.setForeground(new java.awt.Color(255, 215, 0));
        Ingles1_Label1.setText("Ingles");

        Ingles1_Label2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Ingles1_Label2.setForeground(new java.awt.Color(255, 215, 0));
        Ingles1_Label2.setText("¿Cuales son los colores primarios en ingles?");

        Ingles1_Boton1.setBackground(new java.awt.Color(0, 0, 0));
        Ingles1_Boton1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Ingles1_Boton1.setForeground(new java.awt.Color(255, 215, 0));
        Ingles1_Boton1.setText("Red, Blue and Green");
        Ingles1_Boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ingles1_Boton1MouseClicked(evt);
            }
        });

        Ingles1_Boton2.setBackground(new java.awt.Color(0, 0, 0));
        Ingles1_Boton2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Ingles1_Boton2.setForeground(new java.awt.Color(255, 215, 0));
        Ingles1_Boton2.setText("Black, Yellow and Blue");
        Ingles1_Boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ingles1_Boton2MouseClicked(evt);
            }
        });

        Ingles1_Boton3.setBackground(new java.awt.Color(0, 0, 0));
        Ingles1_Boton3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Ingles1_Boton3.setForeground(new java.awt.Color(255, 215, 0));
        Ingles1_Boton3.setText("Red, Blue and Yellow");
        Ingles1_Boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ingles1_Boton3MouseClicked(evt);
            }
        });

        Ingles1_Boton4.setBackground(new java.awt.Color(0, 0, 0));
        Ingles1_Boton4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Ingles1_Boton4.setForeground(new java.awt.Color(255, 215, 0));
        Ingles1_Boton4.setText("Orange, Green and Purple");
        Ingles1_Boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ingles1_Boton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Ingles1_PanelLayout = new javax.swing.GroupLayout(Ingles1_Panel);
        Ingles1_Panel.setLayout(Ingles1_PanelLayout);
        Ingles1_PanelLayout.setHorizontalGroup(
            Ingles1_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ingles1_PanelLayout.createSequentialGroup()
                .addGroup(Ingles1_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Ingles1_PanelLayout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(Ingles1_Label1))
                    .addGroup(Ingles1_PanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(Ingles1_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ingles1_Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ingles1_Label2)
                            .addComponent(Ingles1_Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ingles1_Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ingles1_Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        Ingles1_PanelLayout.setVerticalGroup(
            Ingles1_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ingles1_PanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Ingles1_Label1)
                .addGap(34, 34, 34)
                .addComponent(Ingles1_Label2)
                .addGap(173, 173, 173)
                .addComponent(Ingles1_Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(Ingles1_Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(Ingles1_Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(Ingles1_Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ingles1_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ingles1_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ingles1_Boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ingles1_Boton1MouseClicked
        Ingles1_Boton1.setBackground(Color.RED);
        Ingles1_Boton1.setForeground(Color.WHITE);
        Ingles1_Boton2.setBackground(Color.RED);
        Ingles1_Boton2.setForeground(Color.WHITE);
        Ingles1_Boton3.setBackground(Color.GREEN);
        Ingles1_Boton3.setForeground(Color.WHITE);
        Ingles1_Boton4.setBackground(Color.RED);
        Ingles1_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_Ingles1_Boton1MouseClicked

    private void Ingles1_Boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ingles1_Boton2MouseClicked
        Ingles1_Boton1.setBackground(Color.RED);
        Ingles1_Boton1.setForeground(Color.WHITE);
        Ingles1_Boton2.setBackground(Color.RED);
        Ingles1_Boton2.setForeground(Color.WHITE);
        Ingles1_Boton3.setBackground(Color.GREEN);
        Ingles1_Boton3.setForeground(Color.WHITE);
        Ingles1_Boton4.setBackground(Color.RED);
        Ingles1_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_Ingles1_Boton2MouseClicked

    private void Ingles1_Boton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ingles1_Boton3MouseClicked
        Ingles2 newFrame = new Ingles2();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Ingles1_Boton3MouseClicked

    private void Ingles1_Boton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ingles1_Boton4MouseClicked
        Ingles1_Boton1.setBackground(Color.RED);
        Ingles1_Boton1.setForeground(Color.WHITE);
        Ingles1_Boton2.setBackground(Color.RED);
        Ingles1_Boton2.setForeground(Color.WHITE);
        Ingles1_Boton3.setBackground(Color.GREEN);
        Ingles1_Boton3.setForeground(Color.WHITE);
        Ingles1_Boton4.setBackground(Color.RED);
        Ingles1_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_Ingles1_Boton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingles1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingles1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingles1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingles1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingles1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ingles1_Boton1;
    private javax.swing.JButton Ingles1_Boton2;
    private javax.swing.JButton Ingles1_Boton3;
    private javax.swing.JButton Ingles1_Boton4;
    private javax.swing.JLabel Ingles1_Label1;
    private javax.swing.JLabel Ingles1_Label2;
    private javax.swing.JPanel Ingles1_Panel;
    // End of variables declaration//GEN-END:variables
}
