package Preguntas;

import java.awt.Color;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ET20 - Alumno
 */
public class Ingles3 extends javax.swing.JFrame {

    /**
     * Creates new form Ingles3
     */
    public Ingles3() {
        initComponents();
        setLocationRelativeTo(null); /* Centra la ventana que se abre */
        setResizable(false); /* Le prohibe al usuario editar el tamaño*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ingles3_Panel = new javax.swing.JPanel();
        Ingles3_Label1 = new javax.swing.JLabel();
        Ingles3_Label2 = new javax.swing.JLabel();
        Ingles3_Boton1 = new javax.swing.JButton();
        Ingles3_Boton2 = new javax.swing.JButton();
        Ingles3_Boton3 = new javax.swing.JButton();
        Ingles3_Boton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Ingles3_Panel.setBackground(new java.awt.Color(0, 0, 0));

        Ingles3_Label1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Ingles3_Label1.setForeground(new java.awt.Color(255, 215, 0));
        Ingles3_Label1.setText("Ingles");

        Ingles3_Label2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Ingles3_Label2.setForeground(new java.awt.Color(255, 215, 0));
        Ingles3_Label2.setText("¿Cómo se traduce la frase “I have a dog” al español?");

        Ingles3_Boton1.setBackground(new java.awt.Color(0, 0, 0));
        Ingles3_Boton1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Ingles3_Boton1.setForeground(new java.awt.Color(255, 215, 0));
        Ingles3_Boton1.setText("Vos tenes un perro");
        Ingles3_Boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ingles3_Boton1MouseClicked(evt);
            }
        });
        Ingles3_Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingles3_Boton1ActionPerformed(evt);
            }
        });

        Ingles3_Boton2.setBackground(new java.awt.Color(0, 0, 0));
        Ingles3_Boton2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Ingles3_Boton2.setForeground(new java.awt.Color(255, 215, 0));
        Ingles3_Boton2.setText("Yo tengo un perro");
        Ingles3_Boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ingles3_Boton2MouseClicked(evt);
            }
        });

        Ingles3_Boton3.setBackground(new java.awt.Color(0, 0, 0));
        Ingles3_Boton3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Ingles3_Boton3.setForeground(new java.awt.Color(255, 215, 0));
        Ingles3_Boton3.setText("Yo soy un perro");
        Ingles3_Boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ingles3_Boton3MouseClicked(evt);
            }
        });

        Ingles3_Boton4.setBackground(new java.awt.Color(0, 0, 0));
        Ingles3_Boton4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Ingles3_Boton4.setForeground(new java.awt.Color(255, 215, 0));
        Ingles3_Boton4.setText("El tiene un perro");
        Ingles3_Boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ingles3_Boton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Ingles3_PanelLayout = new javax.swing.GroupLayout(Ingles3_Panel);
        Ingles3_Panel.setLayout(Ingles3_PanelLayout);
        Ingles3_PanelLayout.setHorizontalGroup(
            Ingles3_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ingles3_PanelLayout.createSequentialGroup()
                .addGroup(Ingles3_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Ingles3_PanelLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(Ingles3_Label1))
                    .addGroup(Ingles3_PanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Ingles3_Label2))
                    .addGroup(Ingles3_PanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(Ingles3_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ingles3_Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ingles3_Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ingles3_Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ingles3_Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        Ingles3_PanelLayout.setVerticalGroup(
            Ingles3_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ingles3_PanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Ingles3_Label1)
                .addGap(49, 49, 49)
                .addComponent(Ingles3_Label2)
                .addGap(162, 162, 162)
                .addComponent(Ingles3_Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(Ingles3_Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(Ingles3_Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(Ingles3_Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ingles3_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ingles3_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ingles3_Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingles3_Boton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingles3_Boton1ActionPerformed

    private void Ingles3_Boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ingles3_Boton1MouseClicked
        Ingles3_Boton1.setBackground(Color.RED);
        Ingles3_Boton1.setForeground(Color.WHITE);
        Ingles3_Boton2.setBackground(Color.GREEN);
        Ingles3_Boton2.setForeground(Color.WHITE);
        Ingles3_Boton3.setBackground(Color.RED);
        Ingles3_Boton3.setForeground(Color.WHITE);
        Ingles3_Boton4.setBackground(Color.RED);
        Ingles3_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_Ingles3_Boton1MouseClicked

    private void Ingles3_Boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ingles3_Boton2MouseClicked
        Ingles4 newFrame = new Ingles4();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Ingles3_Boton2MouseClicked

    private void Ingles3_Boton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ingles3_Boton3MouseClicked
        Ingles3_Boton1.setBackground(Color.RED);
        Ingles3_Boton1.setForeground(Color.WHITE);
        Ingles3_Boton2.setBackground(Color.GREEN);
        Ingles3_Boton2.setForeground(Color.WHITE);
        Ingles3_Boton3.setBackground(Color.RED);
        Ingles3_Boton3.setForeground(Color.WHITE);
        Ingles3_Boton4.setBackground(Color.RED);
        Ingles3_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_Ingles3_Boton3MouseClicked

    private void Ingles3_Boton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ingles3_Boton4MouseClicked
        Ingles3_Boton1.setBackground(Color.RED);
        Ingles3_Boton1.setForeground(Color.WHITE);
        Ingles3_Boton2.setBackground(Color.GREEN);
        Ingles3_Boton2.setForeground(Color.WHITE);
        Ingles3_Boton3.setBackground(Color.RED);
        Ingles3_Boton3.setForeground(Color.WHITE);
        Ingles3_Boton4.setBackground(Color.RED);
        Ingles3_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_Ingles3_Boton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingles3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingles3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingles3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingles3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingles3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ingles3_Boton1;
    private javax.swing.JButton Ingles3_Boton2;
    private javax.swing.JButton Ingles3_Boton3;
    private javax.swing.JButton Ingles3_Boton4;
    private javax.swing.JLabel Ingles3_Label1;
    private javax.swing.JLabel Ingles3_Label2;
    private javax.swing.JPanel Ingles3_Panel;
    // End of variables declaration//GEN-END:variables
}
