/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Preguntas;

import java.awt.Color;

/**
 *
 * @author ET20 - Alumno
 */
public class Lengua4 extends javax.swing.JFrame {

    /**
     * Creates new form Lengua4
     */
    public Lengua4() {
        initComponents();
        setLocationRelativeTo(null); /* Centra la ventana que se abre */
        setResizable(false); /* Le prohibe al usuario editar el tamaño*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lengua4_Panel = new javax.swing.JPanel();
        Lengua4_Label1 = new javax.swing.JLabel();
        Lengua4_Label2 = new javax.swing.JLabel();
        Lengua4_Boton1 = new javax.swing.JButton();
        Lengua4_Boton2 = new javax.swing.JButton();
        Lengua4_Boton3 = new javax.swing.JButton();
        Lengua4_Boton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lengua4_Panel.setBackground(new java.awt.Color(0, 0, 0));

        Lengua4_Label1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Lengua4_Label1.setForeground(new java.awt.Color(255, 215, 0));
        Lengua4_Label1.setText("Lengua");

        Lengua4_Label2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Lengua4_Label2.setForeground(new java.awt.Color(255, 215, 0));
        Lengua4_Label2.setText("¿Cuáles son los principales géneros literarios?");

        Lengua4_Boton1.setBackground(new java.awt.Color(0, 0, 0));
        Lengua4_Boton1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Lengua4_Boton1.setForeground(new java.awt.Color(255, 215, 0));
        Lengua4_Boton1.setText("Periodístico, guiones y cuentos");
        Lengua4_Boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lengua4_Boton1MouseClicked(evt);
            }
        });
        Lengua4_Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lengua4_Boton1ActionPerformed(evt);
            }
        });

        Lengua4_Boton2.setBackground(new java.awt.Color(0, 0, 0));
        Lengua4_Boton2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Lengua4_Boton2.setForeground(new java.awt.Color(255, 215, 0));
        Lengua4_Boton2.setText("Lírico, narrativo y dramático");
        Lengua4_Boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lengua4_Boton2MouseClicked(evt);
            }
        });
        Lengua4_Boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lengua4_Boton2ActionPerformed(evt);
            }
        });

        Lengua4_Boton3.setBackground(new java.awt.Color(0, 0, 0));
        Lengua4_Boton3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Lengua4_Boton3.setForeground(new java.awt.Color(255, 215, 0));
        Lengua4_Boton3.setText("Cuentos y novelas");
        Lengua4_Boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lengua4_Boton3MouseClicked(evt);
            }
        });
        Lengua4_Boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lengua4_Boton3ActionPerformed(evt);
            }
        });

        Lengua4_Boton4.setBackground(new java.awt.Color(0, 0, 0));
        Lengua4_Boton4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Lengua4_Boton4.setForeground(new java.awt.Color(255, 215, 0));
        Lengua4_Boton4.setText("Poesía, leyendas y cuentos");
        Lengua4_Boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lengua4_Boton4MouseClicked(evt);
            }
        });
        Lengua4_Boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lengua4_Boton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Lengua4_PanelLayout = new javax.swing.GroupLayout(Lengua4_Panel);
        Lengua4_Panel.setLayout(Lengua4_PanelLayout);
        Lengua4_PanelLayout.setHorizontalGroup(
            Lengua4_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lengua4_PanelLayout.createSequentialGroup()
                .addGroup(Lengua4_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Lengua4_PanelLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(Lengua4_Label1))
                    .addGroup(Lengua4_PanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(Lengua4_Label2))
                    .addGroup(Lengua4_PanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(Lengua4_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lengua4_Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lengua4_Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lengua4_Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lengua4_Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        Lengua4_PanelLayout.setVerticalGroup(
            Lengua4_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lengua4_PanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Lengua4_Label1)
                .addGap(32, 32, 32)
                .addComponent(Lengua4_Label2)
                .addGap(109, 109, 109)
                .addComponent(Lengua4_Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(Lengua4_Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(Lengua4_Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(Lengua4_Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Lengua4_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Lengua4_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Lengua4_Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lengua4_Boton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lengua4_Boton1ActionPerformed

    private void Lengua4_Boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lengua4_Boton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lengua4_Boton2ActionPerformed

    private void Lengua4_Boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lengua4_Boton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lengua4_Boton3ActionPerformed

    private void Lengua4_Boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lengua4_Boton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lengua4_Boton4ActionPerformed

    private void Lengua4_Boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lengua4_Boton1MouseClicked
        // TODO add your handling code here:
        Lengua4_Boton1.setBackground(Color.RED);
        Lengua4_Boton1.setForeground(Color.WHITE);
        Lengua4_Boton2.setBackground(Color.GREEN);
        Lengua4_Boton2.setForeground(Color.WHITE);
        Lengua4_Boton3.setBackground(Color.RED);
        Lengua4_Boton3.setForeground(Color.WHITE);
        Lengua4_Boton4.setBackground(Color.RED);
        Lengua4_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_Lengua4_Boton1MouseClicked

    private void Lengua4_Boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lengua4_Boton2MouseClicked
        // TODO add your handling code here:
        Lengua5 newFrame = new Lengua5();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Lengua4_Boton2MouseClicked

    private void Lengua4_Boton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lengua4_Boton3MouseClicked
        // TODO add your handling code here:
        Lengua4_Boton1.setBackground(Color.RED);
        Lengua4_Boton1.setForeground(Color.WHITE);
        Lengua4_Boton2.setBackground(Color.GREEN);
        Lengua4_Boton2.setForeground(Color.WHITE);
        Lengua4_Boton3.setBackground(Color.RED);
        Lengua4_Boton3.setForeground(Color.WHITE);
        Lengua4_Boton4.setBackground(Color.RED);
        Lengua4_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_Lengua4_Boton3MouseClicked

    private void Lengua4_Boton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lengua4_Boton4MouseClicked
        // TODO add your handling code here:
        Lengua4_Boton1.setBackground(Color.RED);
        Lengua4_Boton1.setForeground(Color.WHITE);
        Lengua4_Boton2.setBackground(Color.GREEN);
        Lengua4_Boton2.setForeground(Color.WHITE);
        Lengua4_Boton3.setBackground(Color.RED);
        Lengua4_Boton3.setForeground(Color.WHITE);
        Lengua4_Boton4.setBackground(Color.RED);
        Lengua4_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_Lengua4_Boton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lengua4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lengua4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lengua4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lengua4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lengua4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Lengua4_Boton1;
    private javax.swing.JButton Lengua4_Boton2;
    private javax.swing.JButton Lengua4_Boton3;
    private javax.swing.JButton Lengua4_Boton4;
    private javax.swing.JLabel Lengua4_Label1;
    private javax.swing.JLabel Lengua4_Label2;
    private javax.swing.JPanel Lengua4_Panel;
    // End of variables declaration//GEN-END:variables
}
