/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Preguntas;

import java.awt.Color;

/**
 *
 * @author ET20 - Alumno
 */
public class Lengua1 extends javax.swing.JFrame {

    /**
     * Creates new form Lengua1
     */
    public Lengua1() {
        initComponents();
        setLocationRelativeTo(null); /* Centra la ventana que se abre */
        setResizable(false); /* Le prohibe al usuario editar el tamaño*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lengua1_Panel = new javax.swing.JPanel();
        Lengua1_Label1 = new javax.swing.JLabel();
        Lengua1_Label2 = new javax.swing.JLabel();
        Lengua1_Boton1 = new javax.swing.JButton();
        Lengua1_Boton2 = new javax.swing.JButton();
        Lengua1_Boton3 = new javax.swing.JButton();
        Lengua1_Boton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lengua1_Panel.setBackground(new java.awt.Color(0, 0, 0));

        Lengua1_Label1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Lengua1_Label1.setForeground(new java.awt.Color(255, 215, 0));
        Lengua1_Label1.setText("Lengua");

        Lengua1_Label2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Lengua1_Label2.setForeground(new java.awt.Color(255, 215, 0));
        Lengua1_Label2.setText("¿Cómo clasificamos las palabras según su acentuación?");

        Lengua1_Boton1.setBackground(new java.awt.Color(0, 0, 0));
        Lengua1_Boton1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Lengua1_Boton1.setForeground(new java.awt.Color(255, 215, 0));
        Lengua1_Boton1.setText("Agudas, graves y esdrújulas");
        Lengua1_Boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lengua1_Boton1MouseClicked(evt);
            }
        });

        Lengua1_Boton2.setBackground(new java.awt.Color(0, 0, 0));
        Lengua1_Boton2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Lengua1_Boton2.setForeground(new java.awt.Color(255, 215, 0));
        Lengua1_Boton2.setText("Sustantivos, adjetivos y verbos");
        Lengua1_Boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lengua1_Boton2MouseClicked(evt);
            }
        });

        Lengua1_Boton3.setBackground(new java.awt.Color(0, 0, 0));
        Lengua1_Boton3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Lengua1_Boton3.setForeground(new java.awt.Color(255, 215, 0));
        Lengua1_Boton3.setText("Agudas, graves y verbos");
        Lengua1_Boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lengua1_Boton3MouseClicked(evt);
            }
        });

        Lengua1_Boton4.setBackground(new java.awt.Color(0, 0, 0));
        Lengua1_Boton4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Lengua1_Boton4.setForeground(new java.awt.Color(255, 215, 0));
        Lengua1_Boton4.setText("Verbos, adverbios y sustantivos");
        Lengua1_Boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lengua1_Boton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Lengua1_PanelLayout = new javax.swing.GroupLayout(Lengua1_Panel);
        Lengua1_Panel.setLayout(Lengua1_PanelLayout);
        Lengua1_PanelLayout.setHorizontalGroup(
            Lengua1_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lengua1_PanelLayout.createSequentialGroup()
                .addGroup(Lengua1_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Lengua1_PanelLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(Lengua1_Label1))
                    .addGroup(Lengua1_PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Lengua1_Label2))
                    .addGroup(Lengua1_PanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(Lengua1_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Lengua1_Boton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lengua1_Boton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(Lengua1_PanelLayout.createSequentialGroup()
                                .addComponent(Lengua1_Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(Lengua1_Boton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        Lengua1_PanelLayout.setVerticalGroup(
            Lengua1_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lengua1_PanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(Lengua1_Label1)
                .addGap(55, 55, 55)
                .addComponent(Lengua1_Label2)
                .addGap(152, 152, 152)
                .addComponent(Lengua1_Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(Lengua1_Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(Lengua1_Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(Lengua1_Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Lengua1_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Lengua1_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Lengua1_Boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lengua1_Boton1MouseClicked
        // TODO add your handling code here:
        Lengua2 newFrame = new Lengua2();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Lengua1_Boton1MouseClicked

    private void Lengua1_Boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lengua1_Boton2MouseClicked
        // TODO add your handling code here:
        Lengua1_Boton1.setBackground(Color.GREEN);
        Lengua1_Boton1.setForeground(Color.WHITE);
        Lengua1_Boton2.setBackground(Color.RED);
        Lengua1_Boton2.setForeground(Color.WHITE);
        Lengua1_Boton3.setBackground(Color.RED);
        Lengua1_Boton3.setForeground(Color.WHITE);
        Lengua1_Boton4.setBackground(Color.RED);
        Lengua1_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_Lengua1_Boton2MouseClicked

    private void Lengua1_Boton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lengua1_Boton3MouseClicked
        // TODO add your handling code here:
        Lengua1_Boton1.setBackground(Color.GREEN);
        Lengua1_Boton1.setForeground(Color.WHITE);
        Lengua1_Boton2.setBackground(Color.RED);
        Lengua1_Boton2.setForeground(Color.WHITE);
        Lengua1_Boton3.setBackground(Color.RED);
        Lengua1_Boton3.setForeground(Color.WHITE);
        Lengua1_Boton4.setBackground(Color.RED);
        Lengua1_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_Lengua1_Boton3MouseClicked

    private void Lengua1_Boton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lengua1_Boton4MouseClicked
        // TODO add your handling code here:
        Lengua1_Boton1.setBackground(Color.GREEN);
        Lengua1_Boton1.setForeground(Color.WHITE);
        Lengua1_Boton2.setBackground(Color.RED);
        Lengua1_Boton2.setForeground(Color.WHITE);
        Lengua1_Boton3.setBackground(Color.RED);
        Lengua1_Boton3.setForeground(Color.WHITE);
        Lengua1_Boton4.setBackground(Color.RED);
        Lengua1_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_Lengua1_Boton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lengua1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lengua1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lengua1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lengua1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lengua1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Lengua1_Boton1;
    private javax.swing.JButton Lengua1_Boton2;
    private javax.swing.JButton Lengua1_Boton3;
    private javax.swing.JButton Lengua1_Boton4;
    private javax.swing.JLabel Lengua1_Label1;
    private javax.swing.JLabel Lengua1_Label2;
    private javax.swing.JPanel Lengua1_Panel;
    // End of variables declaration//GEN-END:variables
}
