/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Preguntas;

import Menu.Juego;
import java.awt.Color;

/**
 *
 * @author ET20 - Alumno
 */
public class Lengua5 extends javax.swing.JFrame {

    /**
     * Creates new form Lengua5
     */
    public Lengua5() {
        initComponents();
        setLocationRelativeTo(null); /* Centra la ventana que se abre */
        setResizable(false); /* Le prohibe al usuario editar el tamaño*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lengua5_Panel = new javax.swing.JPanel();
        Lengua5_Label1 = new javax.swing.JLabel();
        Lengua5_Label2 = new javax.swing.JLabel();
        Lengua5_Boton1 = new javax.swing.JButton();
        Lengua5_Boton2 = new javax.swing.JButton();
        Lengua5_Boton3 = new javax.swing.JButton();
        Lengua5_Boton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lengua5_Panel.setBackground(new java.awt.Color(0, 0, 0));

        Lengua5_Label1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Lengua5_Label1.setForeground(new java.awt.Color(255, 215, 0));
        Lengua5_Label1.setText("Lengua");

        Lengua5_Label2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Lengua5_Label2.setForeground(new java.awt.Color(255, 215, 0));
        Lengua5_Label2.setText("¿Cuáles son las 3 partes de una historia?");

        Lengua5_Boton1.setBackground(new java.awt.Color(0, 0, 0));
        Lengua5_Boton1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Lengua5_Boton1.setForeground(new java.awt.Color(255, 215, 0));
        Lengua5_Boton1.setText("Inicio, nudo y desenlace");
        Lengua5_Boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lengua5_Boton1MouseClicked(evt);
            }
        });
        Lengua5_Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lengua5_Boton1ActionPerformed(evt);
            }
        });

        Lengua5_Boton2.setBackground(new java.awt.Color(0, 0, 0));
        Lengua5_Boton2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Lengua5_Boton2.setForeground(new java.awt.Color(255, 215, 0));
        Lengua5_Boton2.setText("Comienzo, conflicto y solución");
        Lengua5_Boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lengua5_Boton2MouseClicked(evt);
            }
        });
        Lengua5_Boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lengua5_Boton2ActionPerformed(evt);
            }
        });

        Lengua5_Boton3.setBackground(new java.awt.Color(0, 0, 0));
        Lengua5_Boton3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Lengua5_Boton3.setForeground(new java.awt.Color(255, 215, 0));
        Lengua5_Boton3.setText("Principio, problema y final");
        Lengua5_Boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lengua5_Boton3MouseClicked(evt);
            }
        });
        Lengua5_Boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lengua5_Boton3ActionPerformed(evt);
            }
        });

        Lengua5_Boton4.setBackground(new java.awt.Color(0, 0, 0));
        Lengua5_Boton4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Lengua5_Boton4.setForeground(new java.awt.Color(255, 215, 0));
        Lengua5_Boton4.setText("Todas son correctas");
        Lengua5_Boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lengua5_Boton4MouseClicked(evt);
            }
        });
        Lengua5_Boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lengua5_Boton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Lengua5_PanelLayout = new javax.swing.GroupLayout(Lengua5_Panel);
        Lengua5_Panel.setLayout(Lengua5_PanelLayout);
        Lengua5_PanelLayout.setHorizontalGroup(
            Lengua5_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lengua5_PanelLayout.createSequentialGroup()
                .addGroup(Lengua5_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Lengua5_Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lengua5_Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lengua5_Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Lengua5_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Lengua5_PanelLayout.createSequentialGroup()
                            .addGap(206, 206, 206)
                            .addComponent(Lengua5_Label1))
                        .addGroup(Lengua5_PanelLayout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addComponent(Lengua5_Label2))
                        .addGroup(Lengua5_PanelLayout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(Lengua5_Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        Lengua5_PanelLayout.setVerticalGroup(
            Lengua5_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lengua5_PanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Lengua5_Label1)
                .addGap(48, 48, 48)
                .addComponent(Lengua5_Label2)
                .addGap(79, 79, 79)
                .addComponent(Lengua5_Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(Lengua5_Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(Lengua5_Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(Lengua5_Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(316, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Lengua5_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Lengua5_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Lengua5_Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lengua5_Boton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lengua5_Boton1ActionPerformed

    private void Lengua5_Boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lengua5_Boton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lengua5_Boton2ActionPerformed

    private void Lengua5_Boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lengua5_Boton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lengua5_Boton3ActionPerformed

    private void Lengua5_Boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lengua5_Boton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lengua5_Boton4ActionPerformed

    private void Lengua5_Boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lengua5_Boton1MouseClicked
        Lengua5_Boton1.setBackground(Color.RED);
        Lengua5_Boton1.setForeground(Color.WHITE);
        Lengua5_Boton2.setBackground(Color.RED);
        Lengua5_Boton2.setForeground(Color.WHITE);
        Lengua5_Boton3.setBackground(Color.RED);
        Lengua5_Boton3.setForeground(Color.WHITE);
        Lengua5_Boton4.setBackground(Color.GREEN);
        Lengua5_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_Lengua5_Boton1MouseClicked

    private void Lengua5_Boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lengua5_Boton2MouseClicked
        Lengua5_Boton1.setBackground(Color.RED);
        Lengua5_Boton1.setForeground(Color.WHITE);
        Lengua5_Boton2.setBackground(Color.RED);
        Lengua5_Boton2.setForeground(Color.WHITE);
        Lengua5_Boton3.setBackground(Color.RED);
        Lengua5_Boton3.setForeground(Color.WHITE);
        Lengua5_Boton4.setBackground(Color.GREEN);
        Lengua5_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_Lengua5_Boton2MouseClicked

    private void Lengua5_Boton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lengua5_Boton3MouseClicked
        Lengua5_Boton1.setBackground(Color.RED);
        Lengua5_Boton1.setForeground(Color.WHITE);
        Lengua5_Boton2.setBackground(Color.RED);
        Lengua5_Boton2.setForeground(Color.WHITE);
        Lengua5_Boton3.setBackground(Color.RED);
        Lengua5_Boton3.setForeground(Color.WHITE);
        Lengua5_Boton4.setBackground(Color.GREEN);
        Lengua5_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_Lengua5_Boton3MouseClicked

    private void Lengua5_Boton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lengua5_Boton4MouseClicked
        Juego newFrame= new Juego(); 
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Lengua5_Boton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lengua5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lengua5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lengua5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lengua5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lengua5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Lengua5_Boton1;
    private javax.swing.JButton Lengua5_Boton2;
    private javax.swing.JButton Lengua5_Boton3;
    private javax.swing.JButton Lengua5_Boton4;
    private javax.swing.JLabel Lengua5_Label1;
    private javax.swing.JLabel Lengua5_Label2;
    private javax.swing.JPanel Lengua5_Panel;
    // End of variables declaration//GEN-END:variables
}
