/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Preguntas;

import java.awt.Color;

/**
 *
 * @author ET20 - Alumno
 */
public class Matematica4 extends javax.swing.JFrame {

    /**
     * Creates new form Matematica4
     */
    public Matematica4() {
        initComponents();
        setLocationRelativeTo(null); /* Centra la ventana que se abre */
        setResizable(false); /* Le prohibe al usuario editar el tamaño*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Matematica4_Panel = new javax.swing.JPanel();
        Matematica4_Label1 = new javax.swing.JLabel();
        Matematica4_Label2 = new javax.swing.JLabel();
        Matematica4_Boton1 = new javax.swing.JButton();
        Matematica4_Boton2 = new javax.swing.JButton();
        Matematica4_Boton3 = new javax.swing.JButton();
        Matematica4_Boton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Matematica4_Panel.setBackground(new java.awt.Color(0, 0, 0));

        Matematica4_Label1.setBackground(new java.awt.Color(0, 0, 0));
        Matematica4_Label1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Matematica4_Label1.setForeground(new java.awt.Color(255, 215, 0));
        Matematica4_Label1.setText("Matematica");

        Matematica4_Label2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Matematica4_Label2.setForeground(new java.awt.Color(255, 215, 0));
        Matematica4_Label2.setText("9 / 3 = ");

        Matematica4_Boton1.setBackground(new java.awt.Color(0, 0, 0));
        Matematica4_Boton1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Matematica4_Boton1.setForeground(new java.awt.Color(255, 215, 0));
        Matematica4_Boton1.setText("2");
        Matematica4_Boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Matematica4_Boton1MouseClicked(evt);
            }
        });

        Matematica4_Boton2.setBackground(new java.awt.Color(0, 0, 0));
        Matematica4_Boton2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Matematica4_Boton2.setForeground(new java.awt.Color(255, 215, 0));
        Matematica4_Boton2.setText("1");
        Matematica4_Boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Matematica4_Boton2MouseClicked(evt);
            }
        });

        Matematica4_Boton3.setBackground(new java.awt.Color(0, 0, 0));
        Matematica4_Boton3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Matematica4_Boton3.setForeground(new java.awt.Color(255, 215, 0));
        Matematica4_Boton3.setText("9");
        Matematica4_Boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Matematica4_Boton3MouseClicked(evt);
            }
        });

        Matematica4_Boton4.setBackground(new java.awt.Color(0, 0, 0));
        Matematica4_Boton4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Matematica4_Boton4.setForeground(new java.awt.Color(255, 215, 0));
        Matematica4_Boton4.setText("3");
        Matematica4_Boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Matematica4_Boton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Matematica4_PanelLayout = new javax.swing.GroupLayout(Matematica4_Panel);
        Matematica4_Panel.setLayout(Matematica4_PanelLayout);
        Matematica4_PanelLayout.setHorizontalGroup(
            Matematica4_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Matematica4_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Matematica4_Label2)
                .addGap(217, 217, 217))
            .addGroup(Matematica4_PanelLayout.createSequentialGroup()
                .addGroup(Matematica4_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Matematica4_PanelLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(Matematica4_Label1))
                    .addGroup(Matematica4_PanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(Matematica4_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Matematica4_Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Matematica4_Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Matematica4_Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Matematica4_Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        Matematica4_PanelLayout.setVerticalGroup(
            Matematica4_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Matematica4_PanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(Matematica4_Label1)
                .addGap(78, 78, 78)
                .addComponent(Matematica4_Label2)
                .addGap(65, 65, 65)
                .addComponent(Matematica4_Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(Matematica4_Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Matematica4_Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(Matematica4_Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Matematica4_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Matematica4_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Matematica4_Boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Matematica4_Boton1MouseClicked
        Matematica4_Boton1.setBackground(Color.RED);
        Matematica4_Boton1.setForeground(Color.WHITE);
        Matematica4_Boton2.setBackground(Color.RED);
        Matematica4_Boton2.setForeground(Color.WHITE);
        Matematica4_Boton3.setBackground(Color.RED);
        Matematica4_Boton3.setForeground(Color.WHITE);
        Matematica4_Boton4.setBackground(Color.GREEN);
        Matematica4_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_Matematica4_Boton1MouseClicked

    private void Matematica4_Boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Matematica4_Boton2MouseClicked
        Matematica4_Boton1.setBackground(Color.RED);
        Matematica4_Boton1.setForeground(Color.WHITE);
        Matematica4_Boton2.setBackground(Color.RED);
        Matematica4_Boton2.setForeground(Color.WHITE);
        Matematica4_Boton3.setBackground(Color.RED);
        Matematica4_Boton3.setForeground(Color.WHITE);
        Matematica4_Boton4.setBackground(Color.GREEN);
        Matematica4_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_Matematica4_Boton2MouseClicked

    private void Matematica4_Boton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Matematica4_Boton3MouseClicked
        Matematica4_Boton1.setBackground(Color.RED);
        Matematica4_Boton1.setForeground(Color.WHITE);
        Matematica4_Boton2.setBackground(Color.RED);
        Matematica4_Boton2.setForeground(Color.WHITE);
        Matematica4_Boton3.setBackground(Color.RED);
        Matematica4_Boton3.setForeground(Color.WHITE);
        Matematica4_Boton4.setBackground(Color.GREEN);
        Matematica4_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_Matematica4_Boton3MouseClicked

    private void Matematica4_Boton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Matematica4_Boton4MouseClicked
        Matematica5 newFrame = new Matematica5();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Matematica4_Boton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matematica4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matematica4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matematica4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matematica4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Matematica4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Matematica4_Boton1;
    private javax.swing.JButton Matematica4_Boton2;
    private javax.swing.JButton Matematica4_Boton3;
    private javax.swing.JButton Matematica4_Boton4;
    private javax.swing.JLabel Matematica4_Label1;
    private javax.swing.JLabel Matematica4_Label2;
    private javax.swing.JPanel Matematica4_Panel;
    // End of variables declaration//GEN-END:variables
}
