/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Preguntas;

import Menu.Juego;
import java.awt.Color;

/**
 *
 * @author ET20 - Alumno
 */
public class Matematica5 extends javax.swing.JFrame {

    /**
     * Creates new form Matematica5
     */
    public Matematica5() {
        initComponents();
        setLocationRelativeTo(null); /* Centra la ventana que se abre */
        setResizable(false); /* Le prohibe al usuario editar el tamaño*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Matematica5_Panel = new javax.swing.JPanel();
        Matematica5_Label1 = new javax.swing.JLabel();
        Matematica5_Label2 = new javax.swing.JLabel();
        Matematica5_Boton1 = new javax.swing.JButton();
        Matematica5_Boton2 = new javax.swing.JButton();
        Matematica5_Boton3 = new javax.swing.JButton();
        Matematica5_Boton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Matematica5_Panel.setBackground(new java.awt.Color(0, 0, 0));

        Matematica5_Label1.setBackground(new java.awt.Color(0, 0, 0));
        Matematica5_Label1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Matematica5_Label1.setForeground(new java.awt.Color(255, 215, 0));
        Matematica5_Label1.setText("Matematica");

        Matematica5_Label2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Matematica5_Label2.setForeground(new java.awt.Color(255, 215, 0));
        Matematica5_Label2.setText("8 - 6 = ");

        Matematica5_Boton1.setBackground(new java.awt.Color(0, 0, 0));
        Matematica5_Boton1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Matematica5_Boton1.setForeground(new java.awt.Color(255, 215, 0));
        Matematica5_Boton1.setText("14");
        Matematica5_Boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Matematica5_Boton1MouseClicked(evt);
            }
        });

        Matematica5_Boton2.setBackground(new java.awt.Color(0, 0, 0));
        Matematica5_Boton2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Matematica5_Boton2.setForeground(new java.awt.Color(255, 215, 0));
        Matematica5_Boton2.setText("7");
        Matematica5_Boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Matematica5_Boton2MouseClicked(evt);
            }
        });

        Matematica5_Boton3.setBackground(new java.awt.Color(0, 0, 0));
        Matematica5_Boton3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Matematica5_Boton3.setForeground(new java.awt.Color(255, 215, 0));
        Matematica5_Boton3.setText("2");
        Matematica5_Boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Matematica5_Boton3MouseClicked(evt);
            }
        });

        Matematica5_Boton4.setBackground(new java.awt.Color(0, 0, 0));
        Matematica5_Boton4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Matematica5_Boton4.setForeground(new java.awt.Color(255, 215, 0));
        Matematica5_Boton4.setText("4");
        Matematica5_Boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Matematica5_Boton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Matematica5_PanelLayout = new javax.swing.GroupLayout(Matematica5_Panel);
        Matematica5_Panel.setLayout(Matematica5_PanelLayout);
        Matematica5_PanelLayout.setHorizontalGroup(
            Matematica5_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Matematica5_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Matematica5_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Matematica5_PanelLayout.createSequentialGroup()
                        .addComponent(Matematica5_Label1)
                        .addGap(177, 177, 177))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Matematica5_PanelLayout.createSequentialGroup()
                        .addComponent(Matematica5_Label2)
                        .addGap(215, 215, 215))))
            .addGroup(Matematica5_PanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(Matematica5_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Matematica5_Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Matematica5_Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Matematica5_Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Matematica5_Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 57, Short.MAX_VALUE))
        );
        Matematica5_PanelLayout.setVerticalGroup(
            Matematica5_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Matematica5_PanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Matematica5_Label1)
                .addGap(70, 70, 70)
                .addComponent(Matematica5_Label2)
                .addGap(67, 67, 67)
                .addComponent(Matematica5_Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Matematica5_Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(Matematica5_Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(Matematica5_Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Matematica5_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Matematica5_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Matematica5_Boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Matematica5_Boton1MouseClicked
        Matematica5_Boton1.setBackground(Color.RED);
        Matematica5_Boton1.setForeground(Color.WHITE);
        Matematica5_Boton2.setBackground(Color.RED);
        Matematica5_Boton2.setForeground(Color.WHITE);
        Matematica5_Boton3.setBackground(Color.GREEN);
        Matematica5_Boton3.setForeground(Color.WHITE);
        Matematica5_Boton4.setBackground(Color.RED);
        Matematica5_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_Matematica5_Boton1MouseClicked

    private void Matematica5_Boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Matematica5_Boton2MouseClicked
        Matematica5_Boton1.setBackground(Color.RED);
        Matematica5_Boton1.setForeground(Color.WHITE);
        Matematica5_Boton2.setBackground(Color.RED);
        Matematica5_Boton2.setForeground(Color.WHITE);
        Matematica5_Boton3.setBackground(Color.GREEN);
        Matematica5_Boton3.setForeground(Color.WHITE);
        Matematica5_Boton4.setBackground(Color.RED);
        Matematica5_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_Matematica5_Boton2MouseClicked

    private void Matematica5_Boton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Matematica5_Boton3MouseClicked
        Juego newFrame= new Juego(); 
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Matematica5_Boton3MouseClicked

    private void Matematica5_Boton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Matematica5_Boton4MouseClicked
        Matematica5_Boton1.setBackground(Color.RED);
        Matematica5_Boton1.setForeground(Color.WHITE);
        Matematica5_Boton2.setBackground(Color.RED);
        Matematica5_Boton2.setForeground(Color.WHITE);
        Matematica5_Boton3.setBackground(Color.GREEN);
        Matematica5_Boton3.setForeground(Color.WHITE);
        Matematica5_Boton4.setBackground(Color.RED);
        Matematica5_Boton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_Matematica5_Boton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matematica5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matematica5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matematica5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matematica5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Matematica5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Matematica5_Boton1;
    private javax.swing.JButton Matematica5_Boton2;
    private javax.swing.JButton Matematica5_Boton3;
    private javax.swing.JButton Matematica5_Boton4;
    private javax.swing.JLabel Matematica5_Label1;
    private javax.swing.JLabel Matematica5_Label2;
    private javax.swing.JPanel Matematica5_Panel;
    // End of variables declaration//GEN-END:variables
}
